apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hocs-extracts
  name: hocs-extracts
spec:
  maxReplicas: {{.MAX_REPLICAS}}
  minReplicas: {{.MIN_REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hocs-extracts
  targetCPUUtilizationPercentage: 70
